services:
  xgb-inference:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smishing-xgb-inference
    restart: unless-stopped
    environment:
      XGB_MODEL_PATH: /app/models/xgb_final_v1.json
      # XGB_ARTIFACTS_PATH: /app/xgb_train_artifacts.joblib
    ports:
      - "8001:8001"
